// ReSharper disable InconsistentNaming

namespace LDtkUnity.Runtime.Data.Level
{
    public struct LDtkDataLayerInstance
    {
        /// <summary>
        /// Unique String identifier
        /// </summary>
        public string __identifier;
        
        /// <summary>
        /// Layer type (possible values: IntGrid, Entities, Tiles or AutoLayer)
        /// </summary>
        public string __type; 
        
        /// <summary>
        /// Grid-based width
        /// </summary>
        public int __cWid;
        
        /// <summary>
        /// Grid-based height
        /// </summary>
        public int __cHei;
        
        /// <summary>
        /// Grid size
        /// </summary>
        public int __gridSize;

        /// <summary>
        /// Layer opacity as Float [0-1]
        /// </summary>
        public float __opacity;
        
        /// <summary>
        /// Reference to the UID of the level containing this layer instance
        /// </summary>
        public int levelId; 
        
        /// <summary>
        /// Reference the Layer definition UID
        /// </summary>
        public int layerDefUid;
        
        /// <summary>
        /// Horizontal offset in pixels to render this layer, usually 0
        /// </summary>
        public int pxOffsetX;
        
        /// <summary>
        /// Vertical offset in pixels to render this layer, usually 0
        /// </summary>
        public int pxOffsetY;
        
        /// <summary>
        /// Only IntGrid layers
        /// </summary>
        public LDtkDataIntTile[] intGrid;
        
        /// <summary>
        /// Only Auto-layers.
        /// An array containing all tiles generated by Auto-layer rules. The array is already sorted in display order (ie. 1st tile is beneath 2nd, which is beneath 3rd etc.)
        /// </summary>
        public LDtkDataTileInstance[] autoLayerTiles;
        
        /// <summary>
        /// Only Auto-layers.
        /// Random seed used for Auto-Layers rendering
        /// </summary>
        public int seed;
        
        /// <summary>
        /// Only Tile layers
        /// </summary>
        public LDtkDataTileInstance[] gridTiles;
        
        /// <summary>
        /// Only Entity layers
        /// </summary>
        public LDtkDataEntityInstance[] entityInstances;


    }
}