using UnityEditor;

#if UNITY_2020_2_OR_NEWER
using UnityEditor.AssetImporters;
#else
using UnityEditor.Experimental.AssetImporters;
#endif

namespace LDtkUnity.Editor
{
    [CanEditMultipleObjects]
    [CustomEditor(typeof(LDtkConfigImporter))]
    internal sealed class LDtkConfigImporterEditor : ScriptedImporterEditor
    {
        public override void OnInspectorGUI()
        {
            const string msg = "This file is generated by the project importer.\n" +
                               "It contains the configuration data from the project inspector.\n" +
                               "It is only used for telling the levels to reimport when this is changed.";
            EditorGUILayout.HelpBox(msg, MessageType.Info);
            ApplyRevertGUI();
        }
    }
}