//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Samples/Samples/Entities.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.Entities
{
    /// <summary>
    /// LDtk Enum for Entities
    /// </summary>
    public enum ItemType
    {
        Gold,
        Trout,
        Sword,
        Heavy_sword,
        Bow,
        Arrow,
        Staff,
        Magic_ring,
        Healing_potion,
        Mana_potion
    }

    /// <summary>
    /// LDtk Enum for Entities
    /// </summary>
    public enum MonsterType
    {
        Fighter,
        Thief,
        Worm,
        Beholder
    }

    /// <summary>
    /// LDtk Enum for Entities
    /// </summary>
    public enum TriggerCondition
    {
        OnPlayerEnter,
        OnPlayerAttack,
        OnMobEnter
    }
}