using Newtonsoft.Json;

namespace LDtkUnity
{
    public partial class EntityReferenceInfos
    {
        /// <value>
        /// The referenced entity. <br/>
        /// Make sure to call <see cref="LDtkIidBank"/>.<see cref="LDtkIidBank.CacheIidData"/> first!
        /// </value>
        [JsonIgnore] public EntityInstance Entity => EntityIid == null ? null : LDtkIidBank.GetIidData<EntityInstance>(EntityIid);
        
        /// <value>
        /// The layer that this entity is referenced from. <br/>
        /// Make sure to call <see cref="LDtkIidBank"/>.<see cref="LDtkIidBank.CacheIidData"/> first!
        /// </value>
        [JsonIgnore] public LayerInstance Layer => LayerIid == null ? null : LDtkIidBank.GetIidData<LayerInstance>(LayerIid);
        
        /// <value>
        /// The level that this entity is referenced from. <br/>
        /// Make sure to call <see cref="LDtkIidBank"/>.<see cref="LDtkIidBank.CacheIidData"/> first!
        /// </value>
        [JsonIgnore] public Level Level => LevelIid == null ? null : LDtkIidBank.GetIidData<Level>(LevelIid);
        
        /// <value>
        /// The world that this entity is referenced from. <br/>
        /// Make sure to call <see cref="LDtkIidBank"/>.<see cref="LDtkIidBank.CacheIidData"/> first!
        /// </value>
        [JsonIgnore] public World World => WorldIid == null ? null : LDtkIidBank.GetIidData<World>(WorldIid);

        internal static EntityReferenceInfos FromJson(string json)
        {
            return JsonConvert.DeserializeObject<EntityReferenceInfos>(json, Converter.Settings);
        }
    }
    
    //is not auto generated by quick-type.
    /// <summary>
    /// This object is used in Field Instances to describe an EntityRef value.
    /// </summary>
    public partial class EntityReferenceInfos
    {
        /// <summary>
        /// IID of the referred EntityInstance
        /// </summary>
        [JsonProperty("entityIid")]
        public string EntityIid { get; set; }

        /// <summary>
        /// IID of the LayerInstance containing the referred EntityInstance
        /// </summary>
        [JsonProperty("layerIid")]
        public string LayerIid { get; set; }

        /// <summary>
        /// IID of the Level containing the referred EntityInstance
        /// </summary>
        [JsonProperty("levelIid")]
        public string LevelIid { get; set; }
        
        /// <summary>
        /// IID of the World containing the referred EntityInstance
        /// </summary>
        [JsonProperty("worldIid")]
        public string WorldIid { get; set; }
    }
}