//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Samples/Samples/WorldMap_GridVania_layout.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.WorldMap_GridVania_layout
{
    /// <summary>
    /// LDtk Enum for WorldMap_GridVania_layout
    /// </summary>
    public enum ItemType
    {
        Null,
        Meat,
        Gold,
        GoldNuggets,
        Gem,
        Green_gem,
        Healing_potion,
        Spell,
        Armor,
        Bow,
        Ammo,
        Fire_blade,
        Vorpal_blade
    }

    /// <summary>
    /// LDtk Enum for WorldMap_GridVania_layout
    /// </summary>
    public enum RoomType
    {
        Null,
        Entrance,
        Exit,
        Shop,
        Boss,
        Save
    }
}