//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Samples/Samples/AutoLayers_5_OptionalRules.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.AutoLayers_5_OptionalRules
{
    /// <summary>
    /// LDtk Enum for AutoLayers_5_OptionalRules
    /// </summary>
    public enum Tiles_tags
    {
        Water,
        Lava,
        Grass_surface,
        Wood_surface,
        Dirt_surface,
        Stone_surface
    }
}