//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Samples/Samples/Test_file_for_API_showing_all_features.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.Test_file_for_API_showing_all_features
{
    /// <summary>
    /// LDtk Enum for Test_file_for_API_showing_all_features
    /// </summary>
    public enum SomeEnum
    {
        Null,
        A,
        B,
        C,
        D
    }
}