//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Tests/Misc/OtherTechTests/TestAllFieldsLevels.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.TestAllFields
{
    /// <summary>
    /// LDtk Enum for TestAllFields
    /// </summary>
    public enum SomeEnum
    {
        Alpha,
        Beta,
        Omega
    }
}