using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Profiling;

namespace LDtkUnity
{
    /// <summary>
    /// Stores the autogenerated sprites for level backgrounds.
    /// </summary>
    [HelpURL(LDtkHelpURL.SO_ARTIFACT_ASSETS)]
    public sealed class LDtkArtifactAssets : ScriptableObject
    {
        //I've debated if separate level background sprites should generate their own level background sprites.
        //but ive opted against it in favour of quick level reimports. This is okay because the project still has reference to the root infoormation of levels.
        
        //I could consider making it where the level depends on and adds a dependency to the lvl background texture if separate level files are enabled.
        // The reason for this is because the sprite reference could be lost. however, the level depends on 
        //or otherwise, setup dependency frmo the project and store in there.
        //Overall, might be safest option to just always build lvl background in the project. but separate level sounds great
        
        internal const string PROPERTY_BACKGROUNDS = nameof(_backgrounds);

        [SerializeField] internal List<Sprite> _backgrounds = new List<Sprite>();
        
        private readonly Dictionary<string, Sprite> _indexedBackgrounds = new Dictionary<string, Sprite>();
        
        private bool _isIndexed;
        private bool _willResetIndexed;

        /// <value>
        /// Gets all of the background sprite assets used.
        /// </value>
        public List<Sprite> Backgrounds => _backgrounds;

        //todo the importer uses this for now for security reasons. might ease back into the indexed version if it's safe enough
        internal Sprite GetBackgroundSlow(string assetName)
        {
            return _backgrounds.FirstOrDefault(p => p.name == assetName);
        }
        
        /// <summary>
        /// Get a background by name from this import result.
        /// </summary>
        /// <param name="levelName">
        /// The name of the background asset.
        /// </param>
        /// <returns>
        /// The sprite that was generated in this import result.
        /// </returns>
        public Sprite GetBackgroundIndexed(string levelName)
        {
            if (!_isIndexed)
            {
                SetToReset();
                _isIndexed = true;

                foreach (var asset in _backgrounds)
                {
                    if (asset == null)
                    {
                        continue;
                    }
                
                    if (_indexedBackgrounds.ContainsKey(asset.name))
                    {
                        LDtkDebug.LogError("Tried instancing an asset an extra time. this should never happen, and the cached list should all be unique");
                        continue;
                    }
                
                    _indexedBackgrounds.Add(asset.name, asset);
                }
            }

            Profiler.BeginSample($"GetIndexedItem {nameof(Sprite)}");
            if (string.IsNullOrEmpty(levelName))
            {
                LDtkDebug.LogError("GetItem Tried getting an asset without a name");
                Profiler.EndSample();
                return null;
            }
            
            if (_indexedBackgrounds == null)
            {
                LDtkDebug.LogError($"GetItem The instanced dictionary was null when getting artifacts for {nameof(Sprite)} from \"{levelName}\"");
                Profiler.EndSample();
                return null;
            }
            
            if (_indexedBackgrounds.Count == 0)
            {
                LDtkDebug.LogError($"GetItem The instanced dictionary was empty! No values of {nameof(Sprite)} from \"{levelName}\"");
                Profiler.EndSample();
                return null;
            }

            if (_indexedBackgrounds.TryGetValue(levelName, out Sprite item))
            {
                Profiler.EndSample();
                return item;
            }
            
            //LDtkDebug.LogError($"The instanced lookup dictionary doesn't contain {typeof(T).Name} \"{assetName}\"");
            //LDtkDebug.LogError($"The instanced lookup dictionary doesn't contain {typeof(T).Name}");
            Profiler.EndSample();
            return null;
        }

        public bool HasIndexedBackground(string assetName)
        {
            if (string.IsNullOrEmpty(assetName))
                return false;

            if (_indexedBackgrounds.IsNullOrEmpty())
            {
                return false;
            }

            return _indexedBackgrounds.ContainsKey(assetName);
        }

        private void SetToReset()
        {
            if (_willResetIndexed)
            {
                return;
            }

#if UNITY_EDITOR
            _willResetIndexed = true;
            UnityEditor.EditorApplication.delayCall += () =>
            {
                _willResetIndexed = false;
                _isIndexed = false;
                _indexedBackgrounds.Clear();
            };
#endif
        }

        /*internal bool AddSprite(Sprite sprite) //it is expected that all incoming assets are unique.
        {
            if (sprite == null)
            {
                LDtkDebug.LogError("Null sprite when adding an artifact");
                return false;
            }
            _cachedSprites.Add(sprite);
            return true;
        }*/

        internal bool AddBackground(Sprite bg) //it is expected that all incoming assets are unique.
        {
            if (bg == null)
            {
                LDtkDebug.LogError("Null bg when adding an artifact");
                return false;
            }
            _backgrounds.Add(bg);
            return true;
        }
        
        /*internal void HideBackgrounds() => HideGroup(_cachedBackgrounds); //hide the backgrounds so they arent packed in an atlas

        private void HideGroup<T>(List<T> list) where T : Object
        {
            foreach (T obj in list)
            {
                if (obj == null)
                {
                    LDtkDebug.Log("null object");
                    return;
                }
                obj.hideFlags = HideFlags.HideInHierarchy;
            }
        }*/
    }
}