using UnityEngine;
using UnityEngine.Profiling;

namespace LDtkUnity
{
    /// <summary>
    /// The imported level file. (.ldtkt)<br/>
    /// This is generated by the importer. Reference this to access the json data.
    /// </summary>
    [HelpURL(LDtkHelpURL.JSON_TILESET)]
    public class LDtkTilesetFile : LDtkJsonFile<TilesetDefinition>
    {
        /// <value>
        /// Gets the deserialized tileset definition.
        /// </value>
        public override TilesetDefinition FromJson
        {
            get
            {
                Profiler.BeginSample("TilesetDefinition.FromJson");
                TilesetDefinition json = TilesetDefinition.FromJson(_json);
                Profiler.EndSample();
                return json;
            }
        }
    }
}