using UnityEngine;
using UnityEngine.Profiling;

namespace LDtkUnity
{
    /// <summary>
    /// The imported level file. (.ldtkt)<br/>
    /// This is generated by the importer. Reference this to access the json data.
    /// </summary>
    [HelpURL(LDtkHelpURL.JSON_TILESET)]
    public class LDtkTilesetFile : LDtkJsonFile<LDtkTilesetDefinition>
    {
        /// <value>
        /// Gets the deserialized tileset definition.
        /// </value>
        public override LDtkTilesetDefinition FromJson
        {
            get
            {
                Profiler.BeginSample("LDtkTilesetDefinition.FromJson");
                LDtkTilesetDefinition json = LDtkTilesetDefinition.FromJson(_json);
                Profiler.EndSample();
                return json;
            }
        }
    }
}