name: Semantic Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          
      - name: Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print Semantic Release Outputs
        run: |
          echo "Semantic Release Outputs:"
          for output in $(jq -r 'keys[]' <<< "${{ toJson(steps.semantic-release.outputs) }}"); do
            value=$(jq -r ".$output" <<< "${{ toJson(steps.semantic-release.outputs) }}")
            echo "$output: $value"
          done
          
      - name: Discord notification
        if: steps.semantic-release.outputs != null
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '
          [{
            "title": "New Release: ${{ steps.semantic-release.outputs.nextRelease.version }}",
            "description": "Here are the release notes: ${{ steps.semantic-release.outputs.nextRelease.notes }}",
            "footer": {"text": "Pushed by ${{ github.event.head_commit.author.name }}"}
          }]'
