name: Semantic Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          
      - name: Release
        uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Changelog for Discord
        id: read-changelog
        run: echo "::set-output name=changelog::$(cat CHANGELOG.md)"
          
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
          DISCORD_EMBEDS: '[{ "title": "Changelog Details", "description": "${{ steps.read-changelog.outputs.changelog }}", "footer": { "text": "Pushed by ${{github.event.head_commit.author.name}}" } }]'
        uses: Ilshidur/action-discord@master