name: Semantic Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          
      - name: Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print Semantic Release Outputs
        run: |
          echo "Semantic Release Outputs:"
          for key in $(echo "${!SEMANTIC_RELEASE_OUTPUTS[@]}"); do
            echo "$key: ${SEMANTIC_RELEASE_OUTPUTS[$key]}"
          done
        env:
          SEMANTIC_RELEASE_OUTPUTS: ${{ toJson(steps.semantic-release.outputs) }}
          
      - name: Modify release notes
        id: modify_notes
        run: |
          new_release_notes="${{ steps.semantic-release.outputs.new_release_notes }}"
          modified_notes=$(echo "$new_release_notes" | sed 's#\(https\?://[^)]*\)#<\1#g')
          echo "::set-output name=modified_notes::$modified_notes"
          
      - name: Discord notification
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: | 
            ${{ steps.modify_notes.outputs.modified_notes }}