name: Test Runner More Versions

on:
    workflow_dispatch:

jobs:
    testMoreVersions:
        name: Test-${{ matrix.testMode }}-${{ matrix.unityVersion }}
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            fail-fast: false
            matrix:
                testMode:
                    #- playmode
                    - editmode
                unityVersion:
                    - 2019.3.15f1
                    - 2019.4.40f1
                    - 2020.1.17f1
                    - 2020.2.7f1
                    - 2020.3.48f1
                    - 2021.1.28f1
                    - 2021.2.7f1
                    - 2021.3.37f1
                    - 2022.1.14f1
                    - 2022.2.7f1
                    - 2022.3.24f1
                    - 2023.1.7f1
                    - 2023.2.18f1
                    - 6000.0.23f1
        
        steps:
            #Test Checkout
            - uses: actions/checkout@v4.1.4
              with:
                  lfs: true
            
            #Test Cache
            - uses: actions/cache@v4.0.2
              with:
                  path: Library
                  key: Library-${{ matrix.unityVersion }}
                  restore-keys:
                      Library-${{ matrix.unityVersion }}
            
            #Test Runner
            - uses: game-ci/unity-test-runner@v4.1.1
              id: tests
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  projectPath: ${{ matrix.projectPath }}
                  testMode: ${{ matrix.testMode }}
                  artifactsPath: ${{ matrix.testMode }}-artifacts
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  checkName: Test results ${{ matrix.testMode }}-${{ matrix.unityVersion }}
                  unityVersion: ${{ matrix.unityVersion }}
                  customParameters: '-nographics'
            
            #Test Artifact
            - uses: actions/upload-artifact@v4.3.3
              if: always()
              with:
                  name: Test results for ${{ matrix.testMode }}-${{ matrix.unityVersion }}
                  path: ${{ steps.tests.outputs.artifactsPath }}