//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Samples/Samples/Typical_TopDown_example.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.Typical_TopDown_example
{
    /// <summary>
    /// LDtk Enum for Typical_TopDown_example
    /// </summary>
    public enum Item
    {
        Scraps,
        Battery,
        Food,
        Health,
        PowerOrb,
        Key
    }
}